#!/bin/bash

# Based on http://superuser.com/questions/601198/how-can-i-automatically-convert-all-source-code-files-in-a-folder-recursively


tex_file=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)

cat<<EOF >$tex_file   ## Print the tex file header
\documentclass[a4paper]{article}
\usepackage{listings}
\usepackage[usenames,dvipsnames]{color}  %% Allow color names
\lstdefinestyle{customasm}{
  belowcaptionskip=1\baselineskip,
  xleftmargin=\parindent,
  language=C++,    %% Change this to whatever you write in
  breaklines=true, %% Wrap long lines
  basicstyle=\footnotesize\ttfamily,
  commentstyle=\itshape\color{Gray},
  stringstyle=\color{Black},
  keywordstyle=\bfseries\color{OliveGreen},
  identifierstyle=\color{blue},
  xleftmargin=-8em,
}        
\usepackage[colorlinks=true,linkcolor=blue]{hyperref} 
\begin{document}
\tableofcontents

EOF

# find . -type f ! -regex ".*/\..*" ! -name ".*" ! -name "*~" ! -name 'src2pdf'|
find . -name "*\.cpp" -o -name "*\.java" -o -name "*\.txt" | sed 's/^\..//' |
sed 's/^\..//' |                 ## Change ./foo/bar.src to foo/bar.src

while read i; do   ## Loop through each file
  #echo "\newpage" >> $tex_file                              ## start each section on a new page
  echo "\section{$i}" >> $tex_file                           ## Create a section for each file
  echo "\lstinputlisting[style=customasm]{$i}" >>$tex_file   ## Include the file in the PDF
done &&
echo "\end{document}" >> $tex_file &&

pdflatex $tex_file -output-directory . && 
pdflatex $tex_file -output-directory . ## This needs to be run twice for the TOC to be generated

mv $tex_file.pdf notebook.pdf
rm $tex_file.*
rm $tex_file
