#!/bin/bash

# Based on http://superuser.com/questions/601198/how-can-i-automatically-convert-all-source-code-files-in-a-folder-recursively


tex_file=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)

cat<<EOF >$tex_file   ## Print the tex file header
\documentclass[a4paper]{article}
\usepackage[cm]{fullpage}
\usepackage{anyfontsize}
\usepackage{listings}
\usepackage[usenames,dvipsnames]{color}  %% Allow color names
\definecolor{codegreen}{rgb}{0,0.6,0}
\definecolor{codegray}{rgb}{0.5,0.5,0.5}
\definecolor{codepurple}{rgb}{0.58,0,0.82}
\definecolor{backcolour}{rgb}{0.95,0.95,0.92}
\lstdefinestyle{customasm}{
  backgroundcolor=\color{backcolour},   
  commentstyle=\color{codegreen},
  keywordstyle=\color{magenta},
  numberstyle=\tiny\color{codegray},
  stringstyle=\color{codepurple},
  basicstyle=\fontsize{8}{9}\selectfont,
  breakatwhitespace=false,         
  breaklines=true,  %% Wrap long lines
  captionpos=b,
  keepspaces=true,
  numbers=left,
  numbersep=5pt,
  showspaces=false,
  showstringspaces=false,
  showtabs=false,
  tabsize=2
}
\usepackage[colorlinks=true,linkcolor=blue]{hyperref} 
\begin{document}
\tableofcontents
\newpage

EOF

prevsection=""
find . -name "*\.cpp" -o -name "*\.java" -o -name "*\.c" -o -name "*\.txt" | sed 's/^\..//' |
sed 's/^\..//' |                 ## Change ./foo/bar.src to foo/bar.src

while read i; do   ## Loop through each file
  filename=$(basename "$i")
  dirname=$(dirname "$i")
  extension="${i##*.}"
  language="text"
  if [ "$extension" = "c"    ] ; then language="C"    ; fi
  if [ "$extension" = "cpp"  ] ; then language="C++"  ; fi
  if [ "$extension" = "java" ] ; then language="Java" ; fi
  if [ "$prevsection" != "$dirname" ] ; then
    echo "\section{\fontsize{12}{14}\selectfont $dirname}" >> $tex_file
    prevsection=$dirname
  fi
  echo "\subsection{\fontsize{10}{12}\selectfont $filename}" >> $tex_file
  echo "\lstinputlisting[style=customasm,language=$language]{$i} \\*" >>$tex_file   ## Include the file in the PDF
done &&
echo "\end{document}" >> $tex_file &&

pdflatex $tex_file -output-directory . && 
pdflatex $tex_file -output-directory . ## This needs to be run twice for the TOC to be generated

mv $tex_file.pdf notebook.pdf
rm $tex_file.*
rm $tex_file
